// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtuzfFGSfIZx6SdKr5j2sEAfPOjwP2MxA',
    appId: '1:500172344760:web:024a3ff77a2f253306934d',
    messagingSenderId: '500172344760',
    projectId: 'lunadary-app',
    authDomain: 'lunadary-app.firebaseapp.com',
    storageBucket: 'lunadary-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYWED6IKfXKe_3hZcoHLxx2LU0SqtSaY',
    appId: '1:500172344760:android:a53b308477102e6706934d',
    messagingSenderId: '500172344760',
    projectId: 'lunadary-app',
    storageBucket: 'lunadary-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvQmkBb9-vApbX3lpuWnkXKdvM336vcE',
    appId: '1:500172344760:ios:a1c93b0efd4246b206934d',
    messagingSenderId: '500172344760',
    projectId: 'lunadary-app',
    storageBucket: 'lunadary-app.firebasestorage.app',
    iosBundleId: 'com.example.ecomapp',
  );
}
