name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Flutter SDK
      # Using stable channel
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Analyze project source
      - name: Run Flutter analyze
        run: flutter analyze

      # # 5️⃣ Run tests
      # - name: Run tests
      #   run: flutter test --coverage

      # 6️⃣ Build APK (release)
      - name: Build APK
        run: flutter build apk --release

      # Optional: Build AppBundle for Play Store
      # - name: Build App Bundle
      #   run: flutter build appbundle --release

      # 7️⃣ Upload artifact (APK) for later use
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
    


      # Set up Firebase token from service account JSON
      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: "login:ci --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
      
      - name: Upload APK to Firebase App Distribution
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
                --app 1:500172344760:android:8db775938aa2870c06934d \
                --groups "testers" \
                --release-notes "Automated build from GitHub Actions"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      # # Upload to Firebase App Distribution
      # - name: Upload APK to Firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #   run: |
      #     firebase appdistribution:distribute \
      #       build/app/outputs/flutter-apk/app-release.apk \
      #       --app YOUR_FIREBASE_ANDROID_APP_ID \
      #       --groups "testers" \
      #       --release-notes "Automated build from GitHub Actions"